# Only parameters currently supported by the scaffold are listed here.
# TODO(student): Design and implement camera parameters before adding them.
/hikrobot_camera:
  ros__parameters:
     # 相机参数配置
    exposure_time: 5000.0  # 曝光时间 (us)
    gain: 10.0             # 增益 (dB)
    frame_rate: 30.0       # 帧率 (FPS)
    # use_sim_time 是 ROS 2 标准参数，这里保留着，避免影响系统时间
    use_sim_time: false
